default:
  tags:
    - apap

workflow:
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - if: $CI_COMMIT_BRANCH == 'main'

before_script:
  - docker info
  - javac -version


variables:
  IMAGE_OPENJDK_GRADLE: gradle:7.3.3-jdk17-alpine
  IMAGE_DOCKER_DIND: docker:20.10.16

stages:
  - build
  - test
  - build-image
  - publish-image
  - deploy


build:
  image: $IMAGE_OPENJDK_GRADLE
  stage: build
  script:
    - echo "Compiling the code..."
    - cd $CI_PROJECT_DIR/rumahsehat
    - sh gradlew clean assemble
  artifacts:
    paths:
      - rumahsehat/build/libs/TA_B_DEN_69-0.0.1-SNAPSHOT.jar

#static-code-analysis:
#  image: $IMAGE_OPENJDK_GRADLE
#  stage: test
#  script:
#    - echo "Running Static Code Analysis..."
#    - echo "Checking style..."
#    - sh $CI_PROJECT_DIR/gradlew checkstyleMain
#    - echo "Checking duplicated code..."
#    - sh $CI_PROJECT_DIR/gradlew cpdCheck
#    - echo "Checking bugs..."
#    - sh $CI_PROJECT_DIR/gradlew spotbugsMain
#    - echo "Checking code standard..."
#    - sh $CI_PROJECT_DIR/gradlew pmdMain

#unit-test:
#  image: $IMAGE_OPENJDK_GRADLE
#  stage: test
#  script:
#    - echo "Running unit tests..."
#    - sh $CI_PROJECT_DIR/gradlew test -Dspring.profiles.active=test
#
#coverage-test:
#  image: $IMAGE_OPENJDK_GRADLE
#  stage: test
#  needs:
#    - job: unit-test
#  script:
#    - echo "Running coverage tests..."

build-image:
  stage: build-image
  script:
    - echo "Building Docker Image..."
    - docker build -t $REGISTRY_SERVER/zuhal.alimul/apap-069:$CI_COMMIT_SHORT_SHA .
    - docker build -t $REGISTRY_SERVER/zuhal.alimul/apap-069:latest .

publish-image:
  stage: publish-image
  script:
    - echo "Publishing Docker Image..."
    - echo $REGISTRY_SERVER
    - echo $REGISTRY_PASSWORD | docker login --username $REGISTRY_USERNAME --password-stdin $REGISTRY_SERVER
    - docker push $REGISTRY_SERVER/zuhal.alimul/apap-069:$CI_COMMIT_SHORT_SHA
    - docker push $REGISTRY_SERVER/zuhal.alimul/apap-069:latest

deploy:
  stage: deploy
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$DEPLOY_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config

  script:
    - echo "Deploy to server..."
    - rsync -rah ./docker-compose-deploy.yml app.env "${DEPLOY_USERNAME}@${DEPLOY_SERVER}":"~/apap-tk-69"
    - ssh "${DEPLOY_USERNAME}@${DEPLOY_SERVER}" "cd ~/apap-tk-69/ && docker-compose -f docker-compose-deploy.yml down && docker-compose -f docker-compose-deploy.yml pull && docker-compose -f docker-compose-deploy.yml up -d"